#! /usr/bin/env python
import getopt
import math
import os
import subprocess
import sys


prefix = ""
try:
	opts, args = getopt.getopt(sys.argv[1:], "-h", ["m5out-prefix="]) 
except getopt.GetoptError as err:
	print str(err)
	sys.exit(2)

for opt, arg in opts:
   	if opt in ("--m5out-prefix"):
		prefix = arg



cwd = os.getcwd()
work_dir = os.path.dirname(cwd)  + "/experiments/mibench"
print work_dir 
os.chdir(work_dir)

directories = []
for path in os.listdir(work_dir):
	if os.path.isdir(path):
		directories.append(path)
print directories
if prefix != "":
	for directory in directories:
		os.chdir(directory)
		print directory
		command = "mv m5out " + prefix + "-m5out"
		subprocess.call(command, shell=True)
		os.chdir(work_dir)
	os.chdir(cwd)
