#! /usr/bin/env python
import os
import subprocess

cwd = os.getcwd()
work_dir = os.path.dirname(cwd)  + "/experiments/mibench"
print work_dir 
os.chdir(work_dir)

directories = []
for path in os.listdir(work_dir):
	if os.path.isdir(path):
		directories.append(path)
print directories
for directory in directories:
	os.chdir(directory)
	print directory
	command = "make clean; smmmake --clean;"
	subprocess.call(command, shell=True)
	os.chdir(work_dir)
os.chdir(cwd)
