#! /usr/bin/env python
import getopt
import math
import os
import subprocess
import sys


def run():
    	sizes = [2, 4, 8, 16, 32, 64, 128]
	for sramSize in sizes:
		command = "./configure --isram-size " + str(sramSize*1024) + " --dsram-size " + str(sramSize*1024)
		subprocess.call(command, shell=True)
		command = "./run-cache; ./clean; ./run-spm"
		subprocess.call(command, shell=True)
		command = "./stat-mnmt --output experiment_" + str(sramSize) + "KB.xlsx"
		subprocess.call(command, shell=True)

def run_data():
	tile_size = 128
	min_dsize = 2 * 1024
	max_dsize = 64 * 1024
	dsize = min_dsize

	while dsize <=  max_dsize:
		command = "./configure --dcache-size " + str(dsize) + " --tile-size " + str(tile_size) + " --data"
		subprocess.call(command, shell=True)
		command = "./run-cache; ./clean; ./run-spm --data"
		subprocess.call(command, shell=True)
		command = "./tabulate --output experiments_" + str(dsize) + "B.xlsx --data"
		subprocess.call(command, shell=True)
		dsize = dsize * 2	 
	subprocess.call(command, shell=True)


try:
	opts, args = getopt.getopt(sys.argv[1:], "-h", ["data"]) 
except getopt.GetoptError as err:
	print str(err)
	sys.exit(2)
config = 1

for opt, arg in opts:
   	if opt in ("--data"):
		config = 2
if config == 1:
	run()
elif config == 2:
    	run_data()
