#! /usr/bin/env python
import getopt
import math
import os
import subprocess
import sys

#sizes = [2, 4, 8, 16, 32, 64, 128]
sizes = [2,8,16,64]
command = ""
for sramSize in sizes:
	command = command + "./configure --sram-size " + str(sramSize *1024) + "; ./stat --m5out-prefix " + str(sramSize) + "KB"  + " --output " + str(sramSize) + "KB.xlsx; " 
#	command = command + "./stat --code --m5out-prefix " + str(sramSize) + "KB"  + " --output " + str(sramSize) + "KB.xlsx; " 
print command
subprocess.call(command, shell=True)
