#! /usr/bin/env python

import getopt
import os
import subprocess
import sys




# Create a makefile for SMM stack management
def create_makefile_smmstack(arguments="", infile = "", outfile="", stacksize = 256):
	#  make file
	makefile = """
PROGRAM = ${program}

SMMDIR=$(HOME)/Documents/smm

INCLUDEDIRS=
INCLUDE=
LIBDIRS=
LIBS = -lm

OBJECTS = ${original_objects}
OPT_OBJECTS = dma.bc stack_manager.bc ${opt_objects}
PROF_OBJECTS = dma.bc ${prof_objects}
CC=clang
CFLAGS = $(INCLUDEDIRS) $(INCLUDE) -emit-llvm -c -O3 -fno-inline
LDFLAGS = $(LIBDIRS) $(LIBS) -static

all: $(PROGRAM)

$(PROGRAM): $(OBJECTS)
	llvm-link -o basic_$@.bc $(OBJECTS)
	opt -O3 -disable-inlining < basic_$@.bc > $@.bc
	#llvm-dis < $@.bc > $@.ll
	llc -O3 -o $@.s $@.bc 
	$(CC) -o $@ $@.s $(LDFLAGS)
	#objdump -d $@ > $@.dis


%.bc: %${source_file_extension}
	$(CC) $(CFLAGS) $< -o $@

sm: $(OPT_OBJECTS)
	llvm-link -o $@_raw_$(PROGRAM).bc $(OPT_OBJECTS)
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSM.so -smmsm --debug-only=smmssm < $@_raw_$(PROGRAM).bc > $@_$(PROGRAM).bc
	#llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc -O3 -o $@_$(PROGRAM).s $@_$(PROGRAM).bc 
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	#objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis

ssm-cuts:
	ssdm-cuts ssm-wcg/wcg_paths.txt ${stack_size} > wcg_cuts.txt

ssm: $(OPT_OBJECTS)
	llvm-link -o $@_raw_$(PROGRAM).bc $(OPT_OBJECTS)
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSSM.so -smmssm -call-stack-partition wcg_cuts.txt --debug-only=smmssm < $@_raw_$(PROGRAM).bc > $@_$(PROGRAM).bc
	#llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc -O3 -o $@_$(PROGRAM).s $@_$(PROGRAM).bc 
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	#objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis

esm-cuts:
	ssdm-cuts esm-wcg/wcg_paths.txt ${stack_size} > wcg_cuts.txt

esm: $(OPT_OBJECTS)
	llvm-link -o $@_raw_$(PROGRAM).bc $(OPT_OBJECTS)
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMESM.so -smmesm -call-stack-partition wcg_cuts.txt --debug-only=smmesm < $@_raw_$(PROGRAM).bc > $@_$(PROGRAM).bc
	#llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc -O3 -o $@_$(PROGRAM).s $@_$(PROGRAM).bc 
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	#objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis

dma.bc:$(SMMDIR)/common/lib/dma.c
	$(CC) -I$(SMMDIR)/common/include $(CFLAGS) $< -o $@

stack_manager.bc:$(SMMDIR)/stack/lib/stack_manager.c
	$(CC) -I$(SMMDIR)/common/include -I$(SMMDIR)/stack/include $(CFLAGS) $< -o $@

opt_%.bc: %${source_file_extension}
	$(CC) -I$(SMMDIR)/stack/include -include stack_manager.h $(CFLAGS) $< -o $@

prof_%.bc: %${source_file_extension}
	$(CC) $(CFLAGS) $< -o $@

ssm-prof: $(PROF_OBJECTS)
	llvm-link -o $@_$(PROGRAM).bc $(PROF_OBJECTS)

	# Print the stack frame sizes of user-defined functions into wcg_nodes.txt 
	~/Applications/llvm-3.6.0/build/Debug+Asserts/bin/clang -o $@_$(PROGRAM) $@_$(PROGRAM).bc $(LDFLAGS) 2> wcg_nodes.txt

	# Get the call paths and save the result in wcg_paths.txt, based on wcg_nodes.txt
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSSM.so -smmsm-wcg < $@_$(PROGRAM).bc > /dev/null 2> wcg_paths.txt 

	rm -rf ssm-wcg
	mkdir ssm-wcg
	mv wcg_nodes.txt wcg_paths.txt ssm-wcg

esm-prof: $(PROF_OBJECTS)
	llvm-link -o $@_$(PROGRAM).bc $(PROF_OBJECTS)

	# Print the stack frame sizes of user-defined functions into wcg_nodes.txt 
	~/Applications/llvm-3.6.0/build/Debug+Asserts/bin/clang -o $@_$(PROGRAM) $@_$(PROGRAM).bc $(LDFLAGS) 2> wcg_nodes.txt

	# Print the names of the library functions into lib_funcs.txt
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSSM.so -smmsm-libfunc < $@_$(PROGRAM).bc > /dev/null 2> lib_funcs.txt

    	# Get the trace of function calls after turning on the trace of function calls in Gem5
	./runme-prof
	# Get the stack frame sizes of the library functions listed in lib_funcs.txt and add them to wcg_nodes.txt
	libFuncFrameSize lib_funcs.txt wcg_nodes.txt

	# Get the call paths and save the result in wcg_paths.txt, based on wcg_nodes.txt
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSSM.so -smmsm-wcg < $@_$(PROGRAM).bc > /dev/null 2> wcg_paths.txt 

	rm -rf esm-wcg
	mkdir esm-wcg
	mv wcg_nodes.txt wcg_paths.txt esm-wcg

opt:
	make ssm-cuts
	make ssm
	make esm-cuts
	make esm

callgraph:
	opt -O3 -disable-inlining -dot-callgraph < basic_$(PROGRAM).bc
	dot -Tgif callgraph.dot -o basic_$(PROGRAM).gif

clean:
	-rm -rf  $(PROGRAM) *.bc *.ll *.s *.dis *.dot *.gif ${outfile} sm_$(PROGRAM) ssm_$(PROGRAM) esm_$(PROGRAM) ssm-prof_$(PROGRAM) esm-prof_$(PROGRAM) wcg_cuts.txt lib_funcs.txt
    """

	# Create the linker script for SPM setup
	if (not os.path.isfile("spm.ld")): 
		with open('spm.ld', 'w') as outFile:
			inFile = subprocess.Popen("ld --verbose", stdout=subprocess.PIPE, shell=True).communicate()[0].split("\n")
			i = 0
			while i <  range(len(inFile)):
		    		line = inFile[i]
    				while (line.find("==================================================") == -1):
					i = i+1
					line = inFile[i]
				i = i + 1
    				line = inFile[i]
				while (line.find("==================================================") == -1):
					if line.find("executable_start") != -1:
#					  	outFile.write(line.replace("0x400000", "0x000000") + "\n  _spm_begin = .;\n  . = . + 0x100000;\n  _spm_end = .;\n")
					  	outFile.write(line + "\n  _spm_stack_begin = .;\n  . = . + 0x100000;\n  _spm_stack_end = .;\n")
					else:
    						outFile.write(line + "\n")
					i = i+1
					line = inFile[i]
				break;

	# Create the makefile using the created linker script
	if (not os.path.isfile("Makefile")): 
		cwd = os.getcwd()
		files = os.listdir(cwd)
		objects = []
		source_file_extension = ""
		for i in range(len(files)):
			(file, extension) = os.path.splitext(files[i])
			if(extension == ".c" or extension == ".cpp" or extension == ".cc"):
				objects.append(file)
				if source_file_extension == "":
					source_file_extension = extension
		objects = list(set(objects))
		original_objects = ""
		opt_objects = ""
		prof_objects = ""
	   	for i in range(len(objects)):
			original_objects = original_objects + objects[i] + ".bc" + " "
			opt_objects = opt_objects + "opt_" + objects[i] + ".bc" + " "
			prof_objects = prof_objects + "prof_" + objects[i] + ".bc" + " "
		# Use the name of current folder as the name of generated executable file
		program = os.path.basename(cwd)
		with open('Makefile', 'w') as f:
			# make + make opt
			makefile = makefile.replace("${original_objects}", original_objects)
			makefile = makefile.replace("${opt_objects}", opt_objects)
			makefile = makefile.replace("${prof_objects}", prof_objects)
			makefile = makefile.replace("${program}", program)
			makefile = makefile.replace("${source_file_extension}", source_file_extension)
			# make clean
			if (outfile == ""):
				arg_list = arguments.split()
    				for i in range(len(arg_list)):
					if "output" in arg_list[i]:
						outfile = arg_list[i] 
			makefile = makefile.replace("${outfile}", outfile + " sm_" + outfile + " ssm_" + outfile + " esm_" + outfile)
			# make prof
			makefile = makefile.replace("${arguments}", arguments)
			if (infile != ""):
				makefile = makefile.replace("${infile}", "< " + infile)
			else:
				makefile = makefile.replace("${infile}", "")
			makefile = makefile.replace("${stack_size}", str(stacksize))
			f.write(makefile)

def create_runme_smmstack(arguments="", infile = "", outfile=""):
	program = os.path.basename(os.getcwd())
	# Create a runme file 
	if (not os.path.isfile("runme")):
		with open("runme", "w") as f:
			prolog = "#!/bin/sh\nWORK=$HOME\nSIMDIR=$WORK/Applications/gem5"
			text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smm $SIMDIR/configs/example/se.py --cpu-type=atomic -c " + program
			sm_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmsm $SIMDIR/configs/example/se.py --cpu-type=atomic -c sm_" + program
			ssm_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmssm $SIMDIR/configs/example/se.py --cpu-type=atomic -c ssm_" + program
			esm_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmesm $SIMDIR/configs/example/se.py --cpu-type=atomic -c esm_" + program
			if (arguments != ""):
				text = text + " -o \"" + arguments + "\""
				sm_text = sm_text + " -o \"" + arguments.replace("output", "sm_output", 1) + "\""
				ssm_text = ssm_text + " -o \"" + arguments.replace("output", "ssm_output", 1) + "\""
				esm_text = esm_text + " -o \"" + arguments.replace("output", "esm_output", 1) + "\""
			if (infile!= ""):
				text = text + " --input=\"" + infile + "\""
				sm_text = sm_text + " --input=\"" + infile + "\""
				ssm_text = ssm_text + " --input=\"" + infile + "\""
				esm_text = esm_text + " --input=\"" + infile + "\""
			if (outfile != ""):
				text = text + " --output=\"" + outfile + "\""
				sm_text = sm_text + " --output=\"sm_" + outfile + "\""
				ssm_text = ssm_text + " --output=\"ssm_" + outfile + "\""
				esm_text = esm_text + " --output=\"esm_" + outfile + "\""
			f.write(prolog + "\n")
			f.write(text + "\n")
			f.write(sm_text + "\n")
			f.write(ssm_text + "\n")
			f.write(esm_text + "\n")
    		subprocess.Popen("chmod 755 runme", stdout=subprocess.PIPE, shell=True)

	if (not os.path.isfile("runme-prof")):
		with open("runme-prof", "w") as f:
			prolog = "#!/bin/sh\nWORK=$HOME\nSIMDIR=$WORK/Applications/gem5"
			text = "$SIMDIR/build/X86/gem5.opt -q -r -e --stderr-file=simerr -d m5out/smm $SIMDIR/configs/example/se.py --cpu-type=atomic -c " + program
			if (arguments != ""):
				text = text + " -o \"" + arguments + "\""
			if (infile!= ""):
				text = text + " --input=\"" + infile + "\""
			if (outfile != ""):
				text = text + " --output=\"" + outfile + "\""
			f.write(prolog + "\n")
			f.write(text + "\n")
    		subprocess.Popen("chmod 755 runme-prof", stdout=subprocess.PIPE, shell=True)

# Create a makefile for SMM code management
def create_makefile_smmcode(arguments="", infile = "", outfile="", codesize = 0, numregions = 0):
	#  make file
	makefile = """
PROGRAM = ${program}

SMMDIR=$(HOME)/Documents/smm

INCLUDEDIRS=
INCLUDE=
LIBDIRS=
LIBS = -lm

OBJECTS = ${original_objects}
OPT_OBJECTS = dma.bc code_manager.bc ${opt_objects}
CC=clang
CFLAGS = $(INCLUDEDIRS) $(INCLUDE) -emit-llvm -c -O3 -fno-inline
LDFLAGS = $(LIBDIRS) $(LIBS) -static

all: $(PROGRAM)

$(PROGRAM): $(OBJECTS)
	llvm-link -o basic_$@.bc $(OBJECTS)
	opt -O3 -disable-inlining < basic_$@.bc > $@.bc
	llvm-dis < $@.bc > $@.ll
	llc -O3 -o $@.s $@.bc 
	$(CC) -o $@ $@.s $(LDFLAGS)
	objdump -d $@ > $@.dis

overlay:
	# Get user functions names
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMCMH.so -smmcmh-funcinfo --debug-only=smmcm-funcinfo < $(PROGRAM).bc > /dev/null 2> user_defined_funcs.txt
	# Get user functions code sizes
	codeSize user_defined_funcs.txt 2> user_defined_func_size.txt
	-rm user_defined_funcs.txt
	# Get code overlay scheme
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMCMH.so -smmcmh-overlay -func-size user_defined_func_size.txt ${code_size} ${num_regions} < $(PROGRAM).bc > /dev/null 2> mapping.txt

linkerscript:
	# Get the linker script based on overlay scheme
	smmmake --configure-code-linkerscript mapping.txt

cm: $(OPT_OBJECTS)
	llvm-link -o $@_raw_$(PROGRAM).bc $(OPT_OBJECTS)
	# Insert code management functions
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMCM.so -smmcm -overlaying mapping.txt --debug-only=smmcm < $@_raw_$(PROGRAM).bc > $@_$(PROGRAM).bc
	llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc -O3 -o $@_$(PROGRAM).s $@_$(PROGRAM).bc 
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis

ecm: $(OPT_OBJECTS)
	llvm-link -o $@_raw_$(PROGRAM).bc $(OPT_OBJECTS)
	# Insert code management functions based on code overlay scheme
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMECM.so -smmecm -overlaying mapping.txt --debug-only=smmecm < $@_raw_$(PROGRAM).bc > $@_$(PROGRAM).bc
	llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc -O3 -o $@_$(PROGRAM).s $@_$(PROGRAM).bc 
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis

dma.bc:$(SMMDIR)/common/lib/dma.c
	$(CC) -I$(SMMDIR)/common/include -include dma.h $(CFLAGS) $< -o $@

code_manager.bc:$(SMMDIR)/code/lib/code_manager.c
	$(CC) -I$(SMMDIR)/common/include -I$(SMMDIR)/code/include -include code_manager.h $(CFLAGS) $< -o $@

%.bc: %${source_file_extension}
	$(CC) $(CFLAGS) $< -o $@

opt_%.bc: %${source_file_extension}
	$(CC) -I$(SMMDIR)/code/include -include code_manager.h $(CFLAGS) $< -o $@

callgraph:
	opt -O3 -disable-inlining -dot-callgraph < basic_$(PROGRAM).bc
	dot -Tgif callgraph.dot -o basic_$(PROGRAM).gif

clean:
	-rm -rf  $(PROGRAM) *.bc *.ll *.s *.dis *.dot *.gif ${outfile} cm_$(PROGRAM) ecm_$(PROGRAM) user_defined_func_size.txt
    """


	# Create the makefile using the created linker script
	if (not os.path.isfile("Makefile")): 
		cwd = os.getcwd()
		files = os.listdir(cwd)
		objects = []
		source_file_extension = ""
		for i in range(len(files)):
			(file, extension) = os.path.splitext(files[i])
			if(extension == ".c" or extension == ".cpp" or extension == ".cc"):
				objects.append(file)
				if source_file_extension == "":
					source_file_extension = extension
		objects = list(set(objects))
		original_objects = ""
		opt_objects = ""
#		prof_objects = ""
	   	for i in range(len(objects)):
			original_objects = original_objects + objects[i] + ".bc" + " "
			opt_objects = opt_objects + "opt_" + objects[i] + ".bc" + " "
#			prof_objects = prof_objects + "prof_" + objects[i] + ".bc" + " "
		# Use the name of current folder as the name of generated executable file
		program = os.path.basename(cwd)
		with open('Makefile', 'w') as f:
			# make + make opt
			makefile = makefile.replace("${original_objects}", original_objects)
			makefile = makefile.replace("${opt_objects}", opt_objects)
#			makefile = makefile.replace("${prof_objects}", prof_objects)
			makefile = makefile.replace("${program}", program)
			makefile = makefile.replace("${source_file_extension}", source_file_extension)
			# make clean
			if (outfile == ""):
				arg_list = arguments.split()
    				for i in range(len(arg_list)):
					if "output" in arg_list[i]:
						outfile = arg_list[i] 
			if (outfile == ""):
				makefile = makefile.replace("${outfile}", "")
			else:
				makefile = makefile.replace("${outfile}", outfile + " cm_" + outfile + " ecm_" + outfile)
			# make prof
			makefile = makefile.replace("${arguments}", arguments)
			if (infile != ""):
				makefile = makefile.replace("${infile}", "< " + infile)
			else:
				makefile = makefile.replace("${infile}", "")
			if (codesize != 0):
				makefile = makefile.replace("${code_size}", "-code-size " + str(codesize))
			else:
				makefile = makefile.replace("${code_size}", "")
			if (numregions != 0):
				makefile = makefile.replace("${num_regions}", "-num-regions " + str(numregions))
			else:
				makefile = makefile.replace("${num_regions}", "")
			f.write(makefile)


# Create a makefile for SMM code management
def create_linkerscript_smmcode(overlaying):
	# Create the overlay of sections in the linker script from mapping file
	overlay_script = []
	overlays = dict()
	with open(overlaying) as f:
		numSec = int(f.readline())
		for i in range(numSec):
			overlays[i] = {"functions": []}

		for line in f:
			line = line.strip()
    			if line == "":
				continue;
 			tokens = line.split(" ")
   			func = tokens[0]
   			sec = int(tokens[1])
			#print func, " ", sec
   			overlays[sec]['functions'].append(func)

	last_func = ""
	overlay_script.append("\n\n  . = _spm_code_begin;\n")
	for i in range(len(overlays)):
		overlay = overlays[i]
		if i == 0:
			overlay_script.append("  OVERLAY ALIGN(0x10) : AT (_spm_code_end) {\n")
		else:
			overlay_script.append("  OVERLAY ALIGN(0x10) : {\n")
		for func in overlay["functions"]:
			last_func = func
			overlay_script.append("  .%s { *.(%s) }\n" % (func, func))
		overlay_script.append("  }\n")
	overlay_script.append("  . = LOADADDR(.%s) + SIZEOF(.%s);\n" % (last_func, last_func));
	overlay_script.append("  _realign_addr = ALIGN(0x10);\n");
	overlay_script.append("  .realign _realign_addr : AT (_realign_addr) { FILL(0x0) QUAD(0x0) QUAD(0x0) }\n\n");
	#print overlay_script

	# Create the linker script with SPM
#	if (not os.path.isfile("spm.ld")): 
	with open('spm.ld', 'w') as linker_script:
		implicit_linker_script = subprocess.Popen("ld --verbose", stdout=subprocess.PIPE, shell=True).communicate()[0].split("\n")
		i = 0
		while i <  range(len(implicit_linker_script)):
	    		line = implicit_linker_script[i]
    			while (line.find("==================================================") == -1):
				i = i+1
				line = implicit_linker_script[i]
			i = i + 1
    			line = implicit_linker_script[i]
			while (line.find("==================================================") == -1):
				if line.find("executable_start") != -1:
#					linker_script.write(line.replace("0x400000", "0x000000") + "\n  .spm_begin : { FILL(0x0) QUAD(0x0) QUAD(0x0) }\n  . = ALIGN(0x10);\n  _spm_begin = .;\n  . = . + 0x100000;\n  _spm_end = .;\n")
					linker_script.write(line + "\n  . = ALIGN(0x10);\n  _spm_code_begin = .;\n  . = . + 0x100000;\n  _spm_code_end = .;\n")
					linker_script.writelines(overlay_script)
				else:
    					linker_script.write(line + "\n")
				i = i+1
				line = implicit_linker_script[i]
			break;


# Create runme file for a SMM architecture
def create_runme_smmcode(arguments="", infile = "", outfile=""):
	program = os.path.basename(os.getcwd())
	# Create a runme file 
	if (not os.path.isfile("runme")):
		with open("runme", "w") as f:
			prolog = "#!/bin/sh\nWORK=$HOME\nSIMDIR=$WORK/Applications/gem5"
			text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smm $SIMDIR/configs/example/se.py --cpu-type=atomic -c " + program
			cm_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmcm $SIMDIR/configs/example/se.py --cpu-type=atomic -c cm_" + program
			ecm_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmecm $SIMDIR/configs/example/se.py --cpu-type=atomic -c ecm_" + program
			if (arguments != ""):
				text = text + " -o \"" + arguments + "\""
				cm_text = cm_text + " -o \"" + arguments.replace("output", "cm_output", 1) + "\""
				ecm_text = ecm_text + " -o \"" + arguments.replace("output", "ecm_output", 1) + "\""
			if (infile!= ""):
				text = text + " --input=\"" + infile + "\""
				cm_text = cm_text + " --input=\"" + infile + "\""
				ecm_text = ecm_text + " --input=\"" + infile + "\""
			if (outfile != ""):
				text = text + " --output=\"" + outfile + "\""
				cm_text = cm_text + " --output=\"cm_" + outfile + "\""
				ecm_text = ecm_text + " --output=\"ecm_" + outfile + "\""
			f.write(prolog + "\n")
			f.write(text + "\n")
			f.write(cm_text + "\n")
			f.write(ecm_text + "\n")
    		subprocess.Popen("chmod 755 runme", stdout=subprocess.PIPE, shell=True)



# Create a makefile for SMM application management
def create_makefile_smmapp(arguments="", infile = "", outfile="", codesize = 0, stacksize = 0, numregions = 0):
	#  make file
	makefile = """
PROGRAM = ${program}

SMMDIR=$(HOME)/Documents/smm

INCLUDEDIRS=
INCLUDE=
LIBDIRS=
LIBS = -lm

OBJECTS = ${original_objects}
OPT_OBJECTS = dma.bc stack_manager.bc code_manager.bc ${opt_objects}
CC=clang
CFLAGS = $(INCLUDEDIRS) $(INCLUDE) -emit-llvm -c -O3 -fno-inline
LDFLAGS = $(LIBDIRS) $(LIBS) -static

all: $(PROGRAM)

$(PROGRAM): $(OBJECTS)
	llvm-link -o basic_$@.bc $(OBJECTS)
	opt -O3 -disable-inlining < basic_$@.bc > $@.bc
	llvm-dis < $@.bc > $@.ll
	llc -O3 -o $@.s $@.bc 
	$(CC) -o $@ $@.s $(LDFLAGS)
	objdump -d $@ > $@.dis

overlay:
	# Get user functions names
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMCMH.so -smmcmh-funcinfo --debug-only=smmcm-funcinfo < $(PROGRAM).bc > /dev/null 2> user_defined_funcs.txt
	# Get user functions code sizes
	codeSize user_defined_funcs.txt 2> user_defined_func_size.txt
	-rm user_defined_funcs.txt
	# Get code overlay scheme
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMCMH.so -smmcmh-overlay -func-size user_defined_func_size.txt ${code_size} ${num_regions} < $(PROGRAM).bc > /dev/null 2> mapping.txt

linkerscript:
	# Get the linker script based on overlay scheme
	smmmake --configure-app-linkerscript mapping.txt

am: $(OPT_OBJECTS)
	llvm-link -o $@_raw_$(PROGRAM).bc $(OPT_OBJECTS)
	# Insert code management functions
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMAM.so -smmam -overlaying mapping.txt --debug-only=smmam < $@_raw_$(PROGRAM).bc > $@_$(PROGRAM).bc
	#llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc -O3 -o $@_$(PROGRAM).s $@_$(PROGRAM).bc 
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	#objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis

esm-cuts:
	ssdm-cuts esm-wcg/wcg_paths.txt ${stack_size} > wcg_cuts.txt

eam: $(OPT_OBJECTS)
	llvm-link -o $@_raw_$(PROGRAM).bc $(OPT_OBJECTS)
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMEAM.so -smmeam -overlaying mapping.txt -call-stack-partition wcg_cuts.txt --debug-only=smmeam < $@_raw_$(PROGRAM).bc > $@_$(PROGRAM).bc
	#llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc -O3 -o $@_$(PROGRAM).s $@_$(PROGRAM).bc 
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	#objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis

esm-prof: $(PROF_OBJECTS)
	llvm-link -o $@_$(PROGRAM).bc $(PROF_OBJECTS)

	# Print the stack frame sizes of user-defined functions into wcg_nodes.txt 
	~/Applications/llvm-3.6.0/build/Debug+Asserts/bin/clang -o $@_$(PROGRAM) $@_$(PROGRAM).bc $(LDFLAGS) 2> wcg_nodes.txt

	# Print the names of the library functions into lib_funcs.txt
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSSM.so -smmsm-libfunc < $@_$(PROGRAM).bc > /dev/null 2> lib_funcs.txt

    	# Get the trace of function calls after turning on the trace of function calls in Gem5
	./runme-prof
	# Get the stack frame sizes of the library functions listed in lib_funcs.txt and add them to wcg_nodes.txt
	libFuncFrameSize lib_funcs.txt wcg_nodes.txt

	# Get the call paths and save the result in wcg_paths.txt, based on wcg_nodes.txt
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSSM.so -smmsm-wcg < $@_$(PROGRAM).bc > /dev/null 2> wcg_paths.txt 

	rm -rf esm-wcg
	mkdir esm-wcg
	mv wcg_nodes.txt wcg_paths.txt esm-wcg



dma.bc:$(SMMDIR)/common/lib/dma.c
	$(CC) -I$(SMMDIR)/common/include -include dma.h $(CFLAGS) $< -o $@

stack_manager.bc:$(SMMDIR)/stack/lib/stack_manager.c
	$(CC) -I$(SMMDIR)/common/include -I$(SMMDIR)/stack/include -include stack_manager.h $(CFLAGS) $< -o $@

code_manager.bc:$(SMMDIR)/code/lib/code_manager.c
	$(CC) -I$(SMMDIR)/common/include -I$(SMMDIR)/code/include -include code_manager.h $(CFLAGS) $< -o $@

%.bc: %${source_file_extension}
	$(CC) $(CFLAGS) $< -o $@

opt_%.bc: %${source_file_extension}
	$(CC) -I$(SMMDIR)/stack/include -include stack_manager.h -I$(SMMDIR)/code/include -include code_manager.h $(CFLAGS) $< -o $@

clean:
	-rm -rf  $(PROGRAM) *.bc *.ll *.s *.dis *.dot *.gif ${outfile} am_$(PROGRAM) eam_$(PROGRAM) _func_size 
    """


	# Create the makefile using the created linker script
	if (not os.path.isfile("Makefile")): 
		cwd = os.getcwd()
		files = os.listdir(cwd)
		objects = []
		source_file_extension = ""
		for i in range(len(files)):
			(file, extension) = os.path.splitext(files[i])
			if(extension == ".c" or extension == ".cpp" or extension == ".cc"):
				objects.append(file)
				if source_file_extension == "":
					source_file_extension = extension
		objects = list(set(objects))
		original_objects = ""
		opt_objects = ""
#		prof_objects = ""
	   	for i in range(len(objects)):
			original_objects = original_objects + objects[i] + ".bc" + " "
			opt_objects = opt_objects + "opt_" + objects[i] + ".bc" + " "
#			prof_objects = prof_objects + "prof_" + objects[i] + ".bc" + " "
		# Use the name of current folder as the name of generated executable file
		program = os.path.basename(cwd)
		with open('Makefile', 'w') as f:
			# make + make opt
			makefile = makefile.replace("${original_objects}", original_objects)
			makefile = makefile.replace("${opt_objects}", opt_objects)
#			makefile = makefile.replace("${prof_objects}", prof_objects)
			makefile = makefile.replace("${program}", program)
			makefile = makefile.replace("${source_file_extension}", source_file_extension)
			# make clean
			if (outfile == ""):
				arg_list = arguments.split()
    				for i in range(len(arg_list)):
					if "output" in arg_list[i]:
						outfile = arg_list[i] 
			if (outfile == ""):
				makefile = makefile.replace("${outfile}", "")
			else:
				makefile = makefile.replace("${outfile}", outfile + " am_" + outfile)
			# make prof
			makefile = makefile.replace("${arguments}", arguments)
			if (infile != ""):
				makefile = makefile.replace("${infile}", "< " + infile)
			else:
				makefile = makefile.replace("${infile}", "")
			if (stacksize != 0):
				makefile = makefile.replace("${stack_size}", "-stack-size " + str(stacksize))
			else:
				makefile = makefile.replace("${stack_size}", "")
			if (stacksize != 0):
				makefile = makefile.replace("${code_size}", "-code-size " + str(codesize))
			else:
				makefile = makefile.replace("${code_size}", "")
			if (numregions != 0):
				makefile = makefile.replace("${num_regions}", "-num-regions " + str(numregions))
			else:
				makefile = makefile.replace("${num_regions}", "")
			f.write(makefile)


# Create a makefile for SMM applicatoin management
def create_linkerscript_smmapp(overlaying):
	# Create the overlay of sections in the linker script from mapping file
	overlay_script = []
	overlays = dict()
	#print(overlaying)
	with open(overlaying) as f:
		numSec = int(f.readline())
		for i in range(numSec):
			overlays[i] = {"functions": []}

		for line in f:
			line = line.strip()
    			if line == "":
				continue;
 			tokens = line.split(" ")
   			func = tokens[0]
   			sec = int(tokens[1])
			#print func, " ", sec
   			overlays[sec]['functions'].append(func)

	last_func = ""
	overlay_script.append("\n\n  . = _spm_code_begin;\n")
	for i in range(len(overlays)):
		overlay = overlays[i]
		if i == 0:
			overlay_script.append("  OVERLAY ALIGN(0x10) : AT (_spm_code_end) {\n")
		else:
			overlay_script.append("  OVERLAY ALIGN(0x10) : {\n")
		for func in overlay["functions"]:
			last_func = func
			overlay_script.append("  .%s { *.(%s) }\n" % (func, func))
		overlay_script.append("  }\n")
	overlay_script.append("  . = LOADADDR(.%s) + SIZEOF(.%s);\n" % (last_func, last_func));
	overlay_script.append("  _realign_addr = ALIGN(0x10);\n");
	overlay_script.append("  .realign _realign_addr : AT (_realign_addr) { FILL(0x0) QUAD(0x0) QUAD(0x0) }\n\n");
	overlay_script.append("  _spm_stack_begin = .;\n");
	overlay_script.append("  . = . + 0x100000;\n");
	overlay_script.append("  _spm_stack_end = .;\n\n");

	#print overlay_script

	# Create the linker script with SPM
#	if (not os.path.isfile("spm.ld")): 
	with open('spm.ld', 'w') as linker_script:
		implicit_linker_script = subprocess.Popen("ld --verbose", stdout=subprocess.PIPE, shell=True).communicate()[0].split("\n")
		i = 0
		while i <  range(len(implicit_linker_script)):
	    		line = implicit_linker_script[i]
    			while (line.find("==================================================") == -1):
				i = i+1
				line = implicit_linker_script[i]
			i = i + 1
    			line = implicit_linker_script[i]
			while (line.find("==================================================") == -1):
				if line.find("executable_start") != -1:
#					linker_script.write(line.replace("0x400000", "0x000000") + "\n  .spm_begin : { FILL(0x0) QUAD(0x0) QUAD(0x0) }\n  . = ALIGN(0x10);\n  _spm_begin = .;\n  . = . + 0x100000;\n  _spm_end = .;\n")
					linker_script.write(line + "\n  . = ALIGN(0x10);\n  _spm_code_begin = .;\n  . = . + 0x100000;\n  _spm_code_end = .;\n")
					linker_script.writelines(overlay_script)
				else:
    					linker_script.write(line + "\n")
				i = i+1
				line = implicit_linker_script[i]
			break;


# Create runme file for a SMM architecture
def create_runme_smmapp(arguments="", infile = "", outfile=""):
	program = os.path.basename(os.getcwd())
	# Create a runme file 
	if (not os.path.isfile("runme")):
		with open("runme", "w") as f:
			prolog = "#!/bin/sh\nWORK=$HOME\nSIMDIR=$WORK/Applications/gem5"
			text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smm $SIMDIR/configs/example/se.py --cpu-type=atomic -c " + program
			am_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmam $SIMDIR/configs/example/se.py --cpu-type=atomic -c am_" + program
			eam_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmeam $SIMDIR/configs/example/se.py --cpu-type=atomic -c eam_" + program
			if (arguments != ""):
				text = text + " -o \"" + arguments + "\""
				am_text = am_text + " -o \"" + arguments.replace("output", "am_output", 1) + "\""
				eam_text = eam_text + " -o \"" + arguments.replace("output", "eam_output", 1) + "\""
			if (infile!= ""):
				text = text + " --input=\"" + infile + "\""
				am_text = am_text + " --input=\"" + infile + "\""
				eam_text = eam_text + " --input=\"" + infile + "\""
			if (outfile != ""):
				text = text + " --output=\"" + outfile + "\""
				am_text = am_text + " --output=\"am_" + outfile + "\""
				eam_text = eam_text + " --output=\"eam_" + outfile + "\""
			f.write(prolog + "\n")
			f.write(text + "\n")
			f.write(am_text + "\n")
			f.write(eam_text + "\n")
    		subprocess.Popen("chmod 755 runme", stdout=subprocess.PIPE, shell=True)


# Create a makefile for a cache-based architecture
def create_makefile_cache(outfile=""):
	#  Makefile
	makefile = """
PROGRAM = ${program}

INCLUDEDIRS=
INCLUDE=
LIBDIRS=
LIBS = 

OBJECTS = ${original_objects}
CC=clang
CFLAGS = $(INCLUDEDIRS) $(INCLUDE) -c -O3 -fno-inline
LDFLAGS = $(LIBDIRS) $(LIBS) -static

all: $(PROGRAM)

$(PROGRAM): $(OBJECTS)
	llvm-link -o $@.bc $(OBJECTS)
	#opt -O3 -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/LLVMTest.so -test-cg < $@.bc > 
	#llvm-dis < $@.bc > $@.ll
	$(CC) -o $@ $(CFLAGS) $@.bc $(LDFLAGS)
	#objdump -d $@ > $@.dis

%.bc: %${source_file_extension}
	$(CC) $(CFLAGS) -emit-llvm -c $< -o $@

callgraph:
	opt -O3 -disable-inlining -dot-callgraph < basic_$(PROGRAM).bc
	dot -Tgif callgraph.dot -o basic_$(PROGRAM).gif

clean:
	-rm -rf  $(PROGRAM) *.s *.o *.bc *.ll *.dis  ${outfile} *.gif
    """
	# Create the makefile using the created linker script
	if (not os.path.isfile("Makefile")): 
		cwd = os.getcwd()
		files = os.listdir(cwd)
		objects = []
		source_file_extension = ""
		for i in range(len(files)):
			(file, extension) = os.path.splitext(files[i])
			if(extension == ".c" or extension == ".cpp" or extension == ".cc"):
				objects.append(file)
				if source_file_extension == "":
					source_file_extension = extension
		objects = list(set(objects))
		original_objects = ""
	   	for i in range(len(objects)):
			original_objects = original_objects + " " + objects[i] + ".bc"
		# Use the name of current folder as the name of generated executable file
		program = os.path.basename(cwd)
		with open('Makefile', 'w') as f:
			makefile = makefile.replace("${original_objects}", original_objects)
			makefile = makefile.replace("${program}", program)
			makefile = makefile.replace("${source_file_extension}", source_file_extension)
			makefile = makefile.replace("${outfile}", outfile)
			f.write(makefile)


# Create a makefile for using hardware caching
def create_makefile_icache(arguments="", infile = "", outfile=""):
	#  make file
	makefile = """
PROGRAM = ${program}

INCLUDEDIRS=
INCLUDE=
LIBDIRS=
LIBS = -lm

OBJECTS = ${original_objects}
CC=clang
CFLAGS = $(INCLUDEDIRS) $(INCLUDE) -emit-llvm -c -O3 -fno-inline
LDFLAGS = $(LIBDIRS) $(LIBS) -static

all: $(PROGRAM)

$(PROGRAM): $(OBJECTS)
	llvm-link -o basic_$@.bc $(OBJECTS)
#	opt -O3 -disable-inlining < basic_$@.bc > $@.bc
	opt -O3 -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMCMH.so -smmcmh-cache --debug-only=smmcmh < basic_$@.bc > $@.bc
	llvm-dis < $@.bc > $@.ll
	llc -O3 -o $@.s $@.bc 
	$(CC) -o $@ $@.s $(LDFLAGS) -Wl,-T,spm.ld
	objdump -d $@ > $@.dis


%.bc: %${source_file_extension}
	$(CC) $(CFLAGS) $< -o $@

callgraph:
	opt -O3 -disable-inlining -dot-callgraph < basic_$(PROGRAM).bc
	dot -Tgif callgraph.dot -o basic_$(PROGRAM).gif

clean:
	-rm -rf  $(PROGRAM) *.bc *.ll *.s *.dis *.dot *.gif ${outfile} 
    """

	# Create the linker script for SPM setup
	if (not os.path.isfile("spm.ld")): 
		with open('spm.ld', 'w') as outFile:
			inFile = subprocess.Popen("ld --verbose", stdout=subprocess.PIPE, shell=True).communicate()[0].split("\n")
			i = 0
			while i <  range(len(inFile)):
		    		line = inFile[i]
    				while (line.find("==================================================") == -1):
					i = i+1
					line = inFile[i]
				i = i + 1
    				line = inFile[i]
				while (line.find("==================================================") == -1):
					if line.find("executable_start") != -1:
					  	outFile.write(line.replace("0x400000", "0x000000") + "\n  . = ALIGN(0x10); \n  _spm_begin = .;\n  . = . + 0x100000;\n  _spm_end = .;\n  . = _spm_begin; \n  .spm           : { *(.spm) }\n  . = _spm_end;\n")
					else:
    						outFile.write(line + "\n")
					i = i+1
					line = inFile[i]
				break;

	# Create the makefile using the created linker script
	if (not os.path.isfile("Makefile")): 
		cwd = os.getcwd()
		files = os.listdir(cwd)
		objects = []
		source_file_extension = ""
		for i in range(len(files)):
			(file, extension) = os.path.splitext(files[i])
			if(extension == ".c" or extension == ".cpp" or extension == ".cc"):
				objects.append(file)
				if source_file_extension == "":
					source_file_extension = extension
		objects = list(set(objects))
		original_objects = ""
	   	for i in range(len(objects)):
			original_objects = original_objects + objects[i] + ".bc" + " "
		# Use the name of current folder as the name of generated executable file
		program = os.path.basename(cwd)
		with open('Makefile', 'w') as f:
			# make + make opt
			makefile = makefile.replace("${original_objects}", original_objects)
			makefile = makefile.replace("${program}", program)
			makefile = makefile.replace("${source_file_extension}", source_file_extension)
			# make clean
			if (outfile == ""):
				arg_list = arguments.split()
    				for i in range(len(arg_list)):
					if "output" in arg_list[i]:
						outfile = arg_list[i] 
			makefile = makefile.replace("${outfile}", outfile)
			# make prof
			makefile = makefile.replace("${arguments}", arguments)
			if (infile != ""):
				makefile = makefile.replace("${infile}", "< " + infile)
			else:
				makefile = makefile.replace("${infile}", "")
			f.write(makefile)

def create_runme_cache(dsize = "", isize = "", arguments="", infile="", outfile=""):
	program = os.path.basename(os.getcwd())
	# Create a runme script
	if (not os.path.isfile("runme")):
		with open("runme", "w") as f:
			prolog = "#!/bin/sh\nWORK=$HOME\nSIMDIR=$WORK/Applications/gem5-cache"
			text = "$SIMDIR/build/X86/gem5.opt -r -d m5out/cache $SIMDIR/configs/example/se.py  --cpu-type=atomic --caches -c " + program
			if (arguments != ""):
				text = text + " -o \"" + arguments + "\""
			if (infile != ""):
				text = text + " --input=\"" + infile + "\""
			if (outfile != ""):
				text = text + " --output=\"" + outfile + "\""
			if (dsize != ""):
				text = text + " --l1d_size=\"" + dsize +"\""
			if (isize != ""):
				text = text + " --l1i_size=\"" + isize +"\""
			f.write(prolog + "\n")
			f.write(text + "\n")
    		subprocess.Popen("chmod 755 runme", stdout=subprocess.PIPE, shell=True)

		

# Get options
if __name__ == "__main__":
	try:
		opts, args = getopt.getopt(sys.argv[1:], "-h", ["help", "configure-cache", "configure-icache", "configure-stack", "configure-code", "configure-code-linkerscript=", "configure-app", "configure-app-linkerscript=", "stack-size=", "code-size=", "num-regions=", "args=", "input=", "output=", "clean", "l1d_size=", "l1i_size="]) 
	except getopt.GetoptError as err:
		print str(err)
		sys.exit(2)
	arguments = ""
	infile = ""
	outfile = ""
	config = 0
	stacksize = 0
	codesize = 0
	numregions = 0
	overlaying = ""
	dsize = ""
	isize = ""
	for opt, arg in opts:
		if opt in ("-h", "--help"):
			print 'smmmake --configure-cache --configure-icache --configure-stack --configure-code --configure-code-linkerscript --configure-app --configure-app-linkerscript --stack-size --code-size --num-regions --args --input --output --clean --l1d_size --l1i_size'
			sys.exit()
		elif opt in ("--configure-cache"):
			config = 1
		elif opt in ("--configure-stack"):
			config = 2
		elif opt in ("--configure-code"):
			config = 3
		elif opt in ("--configure-code-linkerscript"):
			config = 4
			overlaying = arg
		elif opt in ("--configure-app"):
			config = 5
		elif opt in ("--configure-app-linkerscript"):
			config = 6
			overlaying = arg
		elif opt in ("--configure-icache"):
			config = 7
		elif opt in ("--args"):
			arguments = arg
		elif opt in ("--input"):
			infile = arg
		elif opt in ("--output"):
			outfile = arg
		elif opt in("--stack-size"):
			stacksize = arg
		elif opt in("--code-size"):
			codesize = arg
		elif opt in("--num-regions"):
			numregions = arg
		elif opt in ("--clean"):
			if (os.path.isfile("spm.ld")):
    				subprocess.Popen("rm spm.ld", stdout=subprocess.PIPE, shell=True)
			if (os.path.isfile("Makefile")):
    				subprocess.Popen("rm Makefile", stdout=subprocess.PIPE, shell=True)
			if (os.path.isfile("runme")):
    				subprocess.Popen("rm runme", stdout=subprocess.PIPE, shell=True)
			if (os.path.isfile("runme-prof")):
    				subprocess.Popen("rm runme-prof", stdout=subprocess.PIPE, shell=True)
#			if (os.path.isdir("m5out")):
#    				subprocess.Popen("rm -r m5out", stdout=subprocess.PIPE, shell=True)
		elif opt in ("--l1d_size"):
		      	dsize = arg
		elif opt in ("--l1i_size"):
		      	isize = arg
		else:
			assert False, "unhandled option"

	if config == 1:
		create_makefile_cache(outfile)
		create_runme_cache(dsize, isize, arguments, infile, outfile)
	if config == 2:
		create_makefile_smmstack(arguments, infile, outfile, stacksize)
		create_runme_smmstack(arguments, infile, outfile)
    	if config == 3:
		create_makefile_smmcode(arguments, infile, outfile, codesize, numregions)
		create_runme_smmcode(arguments, infile, outfile)
    	if config == 4:
		create_linkerscript_smmcode(overlaying)
    	if config == 5:
		create_makefile_smmapp(arguments, infile, outfile, codesize, stacksize, numregions)
		create_runme_smmapp(arguments, infile, outfile)
    	if config == 6:
		create_linkerscript_smmapp(overlaying)
    	if config == 7:
		create_makefile_icache(arguments, infile, outfile)
		create_runme_cache(dsize, isize, arguments, infile, outfile)

