#! /usr/bin/env python

import getopt
import glob
import os
import subprocess
import sys




# Create the makefile for SPM management
def create_makefile_spm(arguments="", infile = "", outfile="", stacksize = 0, codesize = 0, numregions = 0, tile = 0):
	#  make file
	makefile = """
PROGRAM = ${program}

SMMDIR=$(HOME)/Documents/smm

INCLUDEDIRS=
INCLUDE=
LIBDIRS=
LIBS = -lm
OPTLVL = -O3

OBJECTS = ${original_objects}
CC=clang
CFLAGS = $(INCLUDEDIRS) $(INCLUDE) $(OPTLVL) -fno-inline
LDFLAGS = $(LIBDIRS) $(LIBS) -static

all: $(PROGRAM)

$(PROGRAM): $(OBJECTS)
	llvm-link -o temp_$@.bc $(OBJECTS)
	opt $(OPTLVL) -disable-inlining < temp_$@.bc > $@.bc
	llvm-dis < $@.bc > $@.ll
	llc -O3 -o $@.s $@.bc 
	$(CC) -o $@ $@.s $(LDFLAGS)
	objdump -d $@ > $@.dis
	-rm temp_$@.bc

basic_$(PROGRAM).bc: $(PROGRAM)
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMBase.so -smm-prolog < $(PROGRAM).bc > basic_$(PROGRAM).bc
	llvm-dis < basic_$(PROGRAM).bc > basic_$(PROGRAM).ll
	-rm temp*_$(PROGRAM).bc

# For stack management

sm: basic_$(PROGRAM).bc dma.bc stack_manager.bc
	llvm-link -o temp_$(PROGRAM).bc dma.bc stack_manager.bc basic_$(PROGRAM).bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSM.so -smmsm --debug-only=smmssm < temp_$(PROGRAM).bc > $@_$(PROGRAM).bc
	#llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc $(OPTLVL) -o $@_$(PROGRAM).s $@_$(PROGRAM).bc 
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	#objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis
	-rm temp*_$(PROGRAM).bc


ssm-profile: $(PROGRAM) 
	# Print the stack frame sizes of user-defined functions into wcg_nodes.txt 
	~/Applications/llvm-3.6.0/build/Debug+Asserts/bin/clang -o $(PROGRAM) $(PROGRAM).bc $(LDFLAGS) 2> wcg_nodes.txt

	# Get the call paths and save the result in wcg_paths.txt, based on wcg_nodes.txt
	opt $(OPTLVL) -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSSM.so -smmsm-wcg < $(PROGRAM).bc > /dev/null 2> wcg_paths.txt 

	# Estimate the stack space  (optional)
	opt $(OPTLVL) -disable-inlining -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSSM.so -smmsm-sse < $(PROGRAM).bc > /dev/null 2> wcg_ssize.txt

	rm -rf ssm-wcg
	mkdir ssm-wcg
	mv wcg_nodes.txt wcg_paths.txt wcg_ssize.txt ssm-wcg

ssm-wcg_cuts.txt:
	ssdm-cuts ssm-wcg/wcg_paths.txt ${stack_size} > ssm-wcg_cuts.txt

ssm: basic_$(PROGRAM).bc dma.bc stack_manager.bc ssm-wcg_cuts.txt 
	llvm-link -o temp_$(PROGRAM).bc dma.bc stack_manager.bc basic_$(PROGRAM).bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSSM.so -smmssm -call-stack-partition ssm-wcg_cuts.txt --debug-only=smmssm < temp_$(PROGRAM).bc > $@_$(PROGRAM).bc
	#llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc $(OPTLVL) -o $@_$(PROGRAM).s $@_$(PROGRAM).bc 
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	#objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis
	-rm temp*_$(PROGRAM).bc


esm-profile: $(PROGRAM)
    	# The trace of function calls in Gem5 must have ben prepared

	# Print the stack frame sizes of user-defined functions into wcg_nodes.txt 
	~/Applications/llvm-3.6.0/build/Debug+Asserts/bin/clang -o $(PROGRAM) $(PROGRAM).bc $(LDFLAGS) 2> wcg_nodes.txt

	# Print the names of the library functions into lib_funcs.txt
	opt $(OPTLVL) -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSSM.so -smmsm-libfunc < $(PROGRAM).bc > /dev/null 2> lib_funcs.txt
	# Get the stack frame sizes of the library functions listed in lib_funcs.txt and add them to wcg_nodes.txt
	libFuncFrameSize lib_funcs.txt wcg_nodes.txt

	# Get the call paths and save the result in wcg_paths.txt, based on wcg_nodes.txt
	opt $(OPTLVL) -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSSM.so -smmsm-wcg < $(PROGRAM).bc > /dev/null 2> wcg_paths.txt 

	-rm -rf esm-wcg
	mkdir esm-wcg
	mv wcg_nodes.txt wcg_paths.txt esm-wcg
	-rm lib_funcs.txt

esm-wcg_cuts.txt:
	ssdm-cuts esm-wcg/wcg_paths.txt ${stack_size} > esm-wcg_cuts.txt

esm: basic_$(PROGRAM).bc dma.bc stack_manager.bc esm-wcg_cuts.txt heap_allocator.bc
	llvm-link -o temp_$(PROGRAM).bc dma.bc stack_manager.bc basic_$(PROGRAM).bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMESM.so -smmesm -call-stack-partition esm-wcg_cuts.txt --debug-only=smmesm < temp_$(PROGRAM).bc > temp1_$(PROGRAM).bc
	llvm-link -o temp2_$(PROGRAM).bc heap_allocator.bc temp1_$(PROGRAM).bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMBase.so -smm-epilog --debug-only=smm < temp2_$(PROGRAM).bc > $@_$(PROGRAM).bc
	llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc $(OPTLVL) -o $@_$(PROGRAM).s $@_$(PROGRAM).bc 
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	#objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis
	-rm temp*_$(PROGRAM).bc

# For code management 

cm-profile: $(PROGRAM)
	# Get user functions names
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMCMH.so -smmcmh-funcname < $(PROGRAM).bc > /dev/null 2> user_funcs.txt
	# Get user functions code sizes
	codeSize user_funcs.txt 2> func_size.txt
	-rm user_funcs.txt

mapping.txt: $(PROGRAM) cm-profile
	# Get code overlay scheme
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMCMH.so -smmcmh-overlay -if-func-size func_size.txt -of-size-regions size_regions.txt ${code_size} ${num_regions} < $(PROGRAM).bc > /dev/null 2> mapping.txt
	# Get the linker script based on overlay scheme
	smmmake --configure-spm-linkerscript mapping.txt

cm: basic_$(PROGRAM).bc dma.bc code_manager.bc mapping.txt 
	llvm-link -o temp_$(PROGRAM).bc dma.bc code_manager.bc basic_$(PROGRAM).bc
	# Insert code management functions
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMCM.so -smmcm -overlaying mapping.txt --debug-only=smmcm < temp_$(PROGRAM).bc > $@_$(PRO
	GRAM).bc
	llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc -O3 -o $@_$(PROGRAM).s $@_$(PROGRAM).bc
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis

ecm: basic_$(PROGRAM).bc dma.bc code_manager.bc mapping.txt heap_allocator.bc
	llvm-link -o temp_$(PROGRAM).bc dma.bc code_manager.bc basic_$(PROGRAM).bc
	# Insert code management functions based on code overlay scheme
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMECM.so -smmecm -overlaying mapping.txt --debug-only=smmecm < temp_$(PROGRAM).bc > temp1_$(PROGRAM).bc
	llvm-link -o temp2_$(PROGRAM).bc heap_allocator.bc temp1_$(PROGRAM).bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMBase.so -smm-cache --debug-only=smm < temp2_$(PROGRAM).bc > $@_$(PROGRAM).bc
	llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc -O3 -o $@_$(PROGRAM).s $@_$(PROGRAM).bc
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis

# For Array management

evm: basic_$(PROGRAM).bc dma.bc heap_allocator.bc
	llvm-link -o temp_$(PROGRAM).bc dma.bc basic_$(PROGRAM).bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMEVM.so -smmevm ${tile} -of-alloc-size array_spm_size.txt < temp_$(PROGRAM).bc > temp1_$(PROGRAM).bc
	llvm-link -o temp2_$(PROGRAM).bc heap_allocator.bc temp1_$(PROGRAM).bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMBase.so -smm-epilog < temp2_$(PROGRAM).bc > $@_$(PROGRAM).bc
	llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc $(OPTLVL) -o $@_$(PROGRAM).s $@_$(PROGRAM).bc 
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	#objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis
	-rm temp*_$(PROGRAM).bc

# For integrated management 

am: basic_$(PROGRAM).bc dma.bc stack_manager.bc  code_manager.bc mapping.txt heap_allocator.bc 
	llvm-link -o temp_$(PROGRAM).bc dma.bc stack_manager.bc code_manager.bc basic_$(PROGRAM).bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMSM.so -smmsm --debug-only=smmsm < temp_$(PROGRAM).bc > temp1_$(PROGRAM).bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMCM.so -smmcm -overlaying mapping.txt --debug-only=smmcm < temp1_$(PROGRAM).bc > $@_$(PROGRAM).bc
	llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc $(OPTLVL) -o $@_$(PROGRAM).s $@_$(PROGRAM).bc 
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	#objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis
	-rm temp_$(PROGRAM).bc

eam: basic_$(PROGRAM).bc dma.bc stack_manager.bc  esm-wcg_cuts.txt code_manager.bc mapping.txt heap_allocator.bc 
	llvm-link -o temp_$(PROGRAM).bc dma.bc stack_manager.bc code_manager.bc basic_$(PROGRAM).bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMESM.so -smmesm -call-stack-partition esm-wcg_cuts.txt < temp_$(PROGRAM).bc > temp1_$(PROGRAM).bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMECM.so -smmecm -overlaying mapping.txt < temp1_$(PROGRAM).bc > temp2_$(PROGRAM).bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMEVM.so -smmevm ${tile} < temp2_$(PROGRAM).bc > temp3_$(PROGRAM).bc
	llvm-link -o temp4_$(PROGRAM).bc heap_allocator.bc temp3_$(PROGRAM).bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMBase.so -smm-epilog --debug-only=smm < temp4_$(PROGRAM).bc > $@_$(PROGRAM).bc
	llvm-dis < $@_$(PROGRAM).bc > $@_$(PROGRAM).ll
	llc -O3 -o $@_$(PROGRAM).s $@_$(PROGRAM).bc 
	$(CC) -o $@_$(PROGRAM) $@_$(PROGRAM).s $(LDFLAGS) -Wl,-T,spm.ld
	#objdump -d $@_$(PROGRAM) > $@_$(PROGRAM).dis
	rm temp*_$(PROGRAM).bc

# Common
dma.bc:$(SMMDIR)/common/lib/dma.c
	$(CC) -I$(SMMDIR)/common/include -include dma.h $(CFLAGS) -emit-llvm -c $< -o $@

stack_manager.bc:$(SMMDIR)/stack/lib/stack_manager.c
	$(CC) -I$(SMMDIR)/common/include -I$(SMMDIR)/stack/include -include stack_manager.h $(CFLAGS) -emit-llvm -c $< -o $@

code_manager.bc:$(SMMDIR)/code/lib/code_manager.c
	$(CC) -I$(SMMDIR)/common/include -I$(SMMDIR)/code/include -include code_manager.h $(CFLAGS) -emit-llvm -c $< -o $@

heap_allocator.bc:$(SMMDIR)/heap/lib/malloc.c
	$(CC) -I$(SMMDIR)/common/include -I$(SMMDIR)/heap/include -include malloc.h $(CFLAGS) -emit-llvm -c $< -o $@

%.bc: %${source_file_extension}
	$(CC) $(CFLAGS) -emit-llvm -c $< -o $@
clean:
	-rm -rf  $(PROGRAM) *.bc *.ll *.s *.dis *.dot *.png ${outfile} sm_$(PROGRAM) ssm_$(PROGRAM) esm_$(PROGRAM) cm_$(PROGRAM) ecm_$(PROGRAM) evm_$(PROGRAM) am_$(PROGRAM) eam_$(PROGRAM) esm-wcg_cuts.txt func_size.txt size_regions.txt mapping.txt array_spm_size.txt
    """


	# Create the makefile using the created linker script
	if (not os.path.isfile("Makefile")): 
		cwd = os.getcwd()
		files = os.listdir(cwd)
		objects = []
		source_file_extension = ""
		for i in range(len(files)):
			(file, extension) = os.path.splitext(files[i])
			if(extension == ".c" or extension == ".cpp" or extension == ".cc"):
				objects.append(file)
				if source_file_extension == "":
					source_file_extension = extension
		objects = list(set(objects))
		original_objects = ""
	   	for i in range(len(objects)):
			original_objects = original_objects + objects[i] + ".bc" + " "
		# Use the name of current folder as the name of generated executable file
		program = os.path.basename(cwd)
		with open('Makefile', 'w') as f:
			# make + make opt
			makefile = makefile.replace("${original_objects}", original_objects)
			makefile = makefile.replace("${program}", program)
			makefile = makefile.replace("${source_file_extension}", source_file_extension)
			# make clean
			if (outfile == ""):
				arg_list = arguments.split()
    				for i in range(len(arg_list)):
					if "output" in arg_list[i]:
						outfile = arg_list[i] 
			if (outfile == ""):
				makefile = makefile.replace("${outfile}", "")
			else:
				makefile = makefile.replace("${outfile}", outfile + " sm_" + outfile + " ssm_" + outfile + " esm_" + outfile + " cm_" + outfile + "ecm_" + outfile + " evm_" + outfile + " am_" + outfile + " eam_" + outfile)
			# make prof
			makefile = makefile.replace("${arguments}", arguments)
			if (infile != ""):
				makefile = makefile.replace("${infile}", "< " + infile)
			else:
				makefile = makefile.replace("${infile}", "")
			if (stacksize != 0):
				makefile = makefile.replace("${stack_size}", str(stacksize))
			else:
				makefile = makefile.replace("${stack_size}", "")
			if (codesize != 0):
				makefile = makefile.replace("${code_size}", "-code-size " + str(codesize))
			else:
				makefile = makefile.replace("${code_size}", "")
			if (numregions != 0):
				makefile = makefile.replace("${num_regions}", "-num-regions " + str(numregions))
			else:
				makefile = makefile.replace("${num_regions}", "")
			if tile != 0:
				makefile = makefile.replace("${tile}", "-tile " + str(tile))
			f.write(makefile)


# Create a makefile for SMM applicatoin management
def create_linkerscript_spm(mapping_file = ""):
	# Create the overlay of sections in the linker script from mapping file
	custom_script = []

	#custom_script.append("\n  . = ALIGN(0x10);\n")
	#custom_script.append("\n  . = __executable_start + 0x100000;\n")
	custom_script.append("\n  . = ALIGN(0x100000);\n")
	custom_script.append("  _spm_begin = .;\n")
	custom_script.append("\n  _spm_reserved_begin = .;\n")
	custom_script.append("  _spm_reserved_end = _spm_reserved_begin + 0x100000;\n");
	custom_script.append("  .management_functions : { *.(management_functions) }\n")
	custom_script.append("  .management_variables : { *.(management_variables) }\n")
	custom_script.append("  . = _spm_reserved_end;\n");

	custom_script.append("\n  _spm_code_begin = .;\n")
	custom_script.append("  _spm_code_end = _spm_code_begin + 0x100000;\n");

	#print(mapping_file)
	if mapping_file != "":
		overlays = dict()
		with open(mapping_file) as f:
			numSec = int(f.readline())
			for i in range(numSec):
				overlays[i] = {"functions": []}

			for line in f:
				line = line.strip()
    				if line == "":
					continue;
 				tokens = line.split(" ")
   				func = tokens[0]
   				sec = int(tokens[1])
				#print func, " ", sec
   				overlays[sec]['functions'].append(func)

		last_func = ""

		for i in range(len(overlays)):
			overlay = overlays[i]
			if i == 0:
				custom_script.append("  OVERLAY ALIGN(0x10) : AT (_spm_code_end) {\n")
			else:
				custom_script.append("  OVERLAY ALIGN(0x10) : {\n")
			for func in overlay["functions"]:
				last_func = func
				custom_script.append("  .%s { *.(%s) }\n" % (func, func))
			custom_script.append("  }\n")
		custom_script.append("  . = LOADADDR(.%s) + SIZEOF(.%s);\n" % (last_func, last_func));
		custom_script.append("  _realign_addr = ALIGN(0x10);\n");
		custom_script.append("  .realign _realign_addr : AT (_realign_addr) { FILL(0x0) QUAD(0x0) QUAD(0x0) }\n");
		#custom_script.append("  ASSERT( (_reaglin_addr <= _spm_code_end), \"Error: Not enough room for code in the SPM\");\n");

	custom_script.append("  . = _spm_code_end + 0x100000;\n");

	custom_script.append("\n  _spm_stack_begin = .;\n");
	custom_script.append("  _spm_stack_end = _spm_stack_begin + 0x100000;\n");
	#custom_script.append("  .spm-stack _spm_stack_begin : AT (_spm_stack_begin) { FILL(0x0) QUAD(0x0) QUAD(0x0) }\n");
	custom_script.append("  . = _spm_stack_end;\n");


	custom_script.append("\n  _spm_array_begin = .;\n");
	custom_script.append("  _spm_array_end = _spm_array_begin + 0x100000;\n");
	#custom_script.append("  .spm-array _spm_array_begin : AT (_spm_array_begin) { FILL(0x0) QUAD(0x0) QUAD(0x0) }\n");
	custom_script.append("  . = _spm_array_end;\n");

	custom_script.append("\n  _spm_end = .;\n")

	custom_script.append("\n  _cacheable_begin = .;\n")

	custom_script.append("\n  _cacheable_stack_begin = .;\n")
	custom_script.append("  _cacheable_stack_end = _cacheable_stack_begin + 0x100000;\n")
	custom_script.append("  . = _cacheable_stack_end;\n\n");

	custom_script.append("\n  _cacheable_heap_begin = .;\n")
	custom_script.append("  _cacheable_heap_end = _cacheable_heap_begin + 0x100000;\n");
	custom_script.append("  . = _cacheable_heap_end;\n");


	custom_script.append("\n  _cacheable_data_begin = .;\n")
	custom_script.append("  _cacheable_data_end = _cacheable_data_begin + 0x100000;\n");
	custom_script.append("  .user_data : { *.(user_data) }\n")
	custom_script.append("  . = _cacheable_data_end;\n");

	custom_script.append("\n  _cacheable_code_begin = .;\n")
	custom_script.append("  _cacheable_code_end = _cacheable_code_begin + 0x100000;\n");
	custom_script.append("  .user_text : { *.(user_text) }\n")
	custom_script.append("  . = _cacheable_code_end;\n");



	custom_script.append("\n  _cacheable_end = .;\n")

	custom_script.append("\n  .smm-guard _cacheable_end : AT (_cacheable_end) { FILL(0x0) QUAD(0x0) QUAD(0x0) }\n\n");

	custom_script.append("\n")



	#print custom_script

	# Create the linker script with SPM
#	if (not os.path.isfile("spm.ld")): 
	with open('spm.ld', 'w') as linker_script:
		implicit_linker_script = subprocess.Popen("ld --verbose", stdout=subprocess.PIPE, shell=True).communicate()[0].split("\n")
		i = 0
		while i <  range(len(implicit_linker_script)):
	    		line = implicit_linker_script[i]
    			while (line.find("==================================================") == -1):
				i = i+1
				line = implicit_linker_script[i]
			i = i + 1
    			line = implicit_linker_script[i]
			while (line.find("==================================================") == -1):
				if line.find("executable_start") != -1:
#					linker_script.write(line.replace("0x400000", "0x000000") + "\n  .spm_begin : { FILL(0x0) QUAD(0x0) QUAD(0x0) }\n  . = ALIGN(0x10);\n  _spm_begin = .;\n  . = . + 0x100000;\n  _spm_end = .;\n")
					#linker_script.write(line + "\n  . = ALIGN(0x10);\n  _spm_code_begin = .;\n  . = . + 0x100000;\n  _spm_code_end = .;\n")
					linker_script.write(line)
					linker_script.writelines(custom_script)
				else:
    					linker_script.write(line + "\n")
				i = i+1
				line = implicit_linker_script[i]
			break;


# Create the runme file for SPM architecture
def create_runme_smmapp(arguments="", infile = "", outfile="", l1d_size = 0, l1i_size = 0):
	program = os.path.basename(os.getcwd())
	# Create a runme file 
	if (not os.path.isfile("am_runme")):
		with open("am_runme", "w") as f:
			prolog = "#!/bin/sh\nWORK=$HOME\nSIMDIR=$WORK/Applications/gem5"
			text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smm $SIMDIR/configs/example/se.py --cpu-type=atomic -c " + program
			am_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmam $SIMDIR/configs/example/se.py --cpu-type=atomic -c am_" + program
			eam_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmeam $SIMDIR/configs/example/se.py --cpu-type=atomic -c eam_" + program
			if (arguments != ""):
				text = text + " -o \"" + arguments + "\""
				am_text = am_text + " -o \"" + arguments.replace("output", "am_output", 1) + "\""
				eam_text = eam_text + " -o \"" + arguments.replace("output", "eam_output", 1) + "\""
			if (infile!= ""):
				text = text + " --input=\"" + infile + "\""
				am_text = am_text + " --input=\"" + infile + "\""
				eam_text = eam_text + " --input=\"" + infile + "\""
			if (outfile != ""):
				text = text + " --output=\"" + outfile + "\""
				am_text = am_text + " --output=\"am_" + outfile + "\""
				eam_text = eam_text + " --output=\"eam_" + outfile + "\""
			cache_params = ""
			if l1d_size  or l1i_size:
				cache_params = " --caches"
				if l1d_size:
					cache_params = cache_params + " --l1d_size " + str(l1d_size)
				if l1i_size:
					cache_params = cache_params + " --l1i_size " + str(l1i_size)
			f.write(prolog + "\n")
			f.write(text + cache_params + "\n")
			#f.write(am_text + cache_params + "\n")
			f.write(eam_text + cache_params + "\n")
    		subprocess.Popen("chmod +x am_runme", stdout=subprocess.PIPE, shell=True)

	if (not os.path.isfile("sm_runme-prof")):
		with open("sm_runme-prof", "w") as f:
			prolog = "#!/bin/sh\nWORK=$HOME\nSIMDIR=$WORK/Applications/gem5"
			text = "$SIMDIR/build/X86/gem5.opt -q -r -e --stderr-file=simerr -d m5out/smm $SIMDIR/configs/example/se.py --cpu-type=atomic -c " + program
			if (arguments != ""):
				text = text + " -o \"" + arguments + "\""
			if (infile!= ""):
				text = text + " --input=\"" + infile + "\""
			if (outfile != ""):
				text = text + " --output=\"" + outfile + "\""
			f.write(prolog + "\n")
			f.write(text + "\n")
    		subprocess.Popen("chmod +x sm_runme-prof", stdout=subprocess.PIPE, shell=True)

# Create the runme file for stack management
def create_runme_smmstack(arguments="", infile = "", outfile="", l1d_size = 0, l1i_size = 0):
	program = os.path.basename(os.getcwd())
	# Create a runme file 
	if (not os.path.isfile("sm_runme")):
		with open("sm_runme", "w") as f:
			prolog = "#!/bin/sh\nWORK=$HOME\nSIMDIR=$WORK/Applications/gem5"
			text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smm $SIMDIR/configs/example/se.py --cpu-type=atomic -c " + program
			sm_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmsm $SIMDIR/configs/example/se.py --cpu-type=atomic -c sm_" + program
			ssm_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmssm $SIMDIR/configs/example/se.py --cpu-type=atomic -c ssm_" + program
			esm_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmesm $SIMDIR/configs/example/se.py --cpu-type=atomic -c esm_" + program
			if (arguments != ""):
				text = text + " -o \"" + arguments + "\""
				sm_text = sm_text + " -o \"" + arguments.replace("output", "sm_output", 1) + "\""
				ssm_text = ssm_text + " -o \"" + arguments.replace("output", "ssm_output", 1) + "\""
				esm_text = esm_text + " -o \"" + arguments.replace("output", "esm_output", 1) + "\""
			if (infile!= ""):
				text = text + " --input=\"" + infile + "\""
				sm_text = sm_text + " --input=\"" + infile + "\""
				ssm_text = ssm_text + " --input=\"" + infile + "\""
				esm_text = esm_text + " --input=\"" + infile + "\""
			if (outfile != ""):
				text = text + " --output=\"" + outfile + "\""
				sm_text = sm_text + " --output=\"sm_" + outfile + "\""
				ssm_text = ssm_text + " --output=\"ssm_" + outfile + "\""
				esm_text = esm_text + " --output=\"esm_" + outfile + "\""

			cache_params = ""
			if l1d_size  or l1i_size:
				cache_params = " --caches"
				if l1d_size:
					cache_params = cache_params + " --l1d_size " + str(l1d_size)
				if l1i_size:
					cache_params = cache_params + " --l1i_size " + str(l1i_size)

			f.write(prolog + "\n")
			f.write(text + cache_params + "\n")
			#f.write(sm_text + cache_params + "\n")
			#f.write(ssm_text + cache_params + "\n")
			f.write(esm_text + cache_params + "\n")
    		subprocess.Popen("chmod +x sm_runme", stdout=subprocess.PIPE, shell=True)

	if (not os.path.isfile("sm_runme-prof")):
		with open("sm_runme-prof", "w") as f:
			prolog = "#!/bin/sh\nWORK=$HOME\nSIMDIR=$WORK/Applications/gem5"
			text = "$SIMDIR/build/X86/gem5.opt -q -r -e --stderr-file=simerr -d m5out/smm $SIMDIR/configs/example/se.py --cpu-type=atomic -c " + program
			if (arguments != ""):
				text = text + " -o \"" + arguments + "\""
			if (infile!= ""):
				text = text + " --input=\"" + infile + "\""
			if (outfile != ""):
				text = text + " --output=\"" + outfile + "\""
			f.write(prolog + "\n")
			f.write(text + "\n")
    		subprocess.Popen("chmod +x sm_runme-prof", stdout=subprocess.PIPE, shell=True)

# Create the runme file for code management
def create_runme_smmcode(arguments="", infile = "", outfile=""):
	program = os.path.basename(os.getcwd())
	# Create a runme file 
	if (not os.path.isfile("cm_runme")):
		with open("cm_runme", "w") as f:
			prolog = "#!/bin/sh\nWORK=$HOME\nSIMDIR=$WORK/Applications/gem5"
			text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smm $SIMDIR/configs/example/se.py --cpu-type=atomic -c " + program
			cm_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmcm $SIMDIR/configs/example/se.py --cpu-type=atomic -c cm_" + program
			ecm_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmecm $SIMDIR/configs/example/se.py --cpu-type=atomic -c ecm_" + program
			if (arguments != ""):
				text = text + " -o \"" + arguments + "\""
				cm_text = cm_text + " -o \"" + arguments.replace("output", "cm_output", 1) + "\""
				ecm_text = ecm_text + " -o \"" + arguments.replace("output", "ecm_output", 1) + "\""
			if (infile!= ""):
				text = text + " --input=\"" + infile + "\""
				cm_text = cm_text + " --input=\"" + infile + "\""
				ecm_text = ecm_text + " --input=\"" + infile + "\""
			if (outfile != ""):
				text = text + " --output=\"" + outfile + "\""
				cm_text = cm_text + " --output=\"cm_" + outfile + "\""
				ecm_text = ecm_text + " --output=\"ecm_" + outfile + "\""
			f.write(prolog + "\n")
			f.write(text + "\n")
			f.write(cm_text + "\n")
			f.write(ecm_text + "\n")
    		subprocess.Popen("chmod +x cm_runme", stdout=subprocess.PIPE, shell=True)


def create_runme_smmarray(arguments="", infile = "", outfile="", l1d_size = 0, l1i_size = 0):
	program = os.path.basename(os.getcwd())
	# Create a runme file 
	if (not os.path.isfile("vm_runme")):
		with open("vm_runme", "w") as f:
			prolog = "#!/bin/sh\nWORK=$HOME\nSIMDIR=$WORK/Applications/gem5"
			text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smm $SIMDIR/configs/example/se.py --cpu-type=atomic -c " + program
			evm_text = "$SIMDIR/build/X86/gem5.opt -q -r -d m5out/spm/smmevm $SIMDIR/configs/example/se.py --cpu-type=atomic -c evm_" + program
			if (arguments != ""):
				text = text + " -o \"" + arguments + "\""
				evm_text = evm_text + " -o \"" + arguments.replace("output", "evm_output", 1) + "\""
			if (infile!= ""):
				text = text + " --input=\"" + infile + "\""
				evm_text = evm_text + " --input=\"" + infile + "\""
			if (outfile != ""):
				text = text + " --output=\"" + outfile + "\""
				evm_text = evm_text + " --output=\"evm_" + outfile + "\""

			cache_params = ""
			if l1d_size  or l1i_size:
				cache_params = " --caches"
				if l1d_size:
					cache_params = cache_params + " --l1d_size " + str(l1d_size)
				if l1i_size:
					cache_params = cache_params + " --l1i_size " + str(l1i_size)

			f.write(prolog + "\n")
			f.write(text + cache_params + "\n")
			f.write(evm_text + cache_params + "\n")
    		subprocess.Popen("chmod +x vm_runme", stdout=subprocess.PIPE, shell=True)





# Create a makefile for a cache-based architecture
def create_makefile_cache(outfile=""):
	#  Makefile
	makefile = """
PROGRAM = ${program}

SMMDIR=$(HOME)/Documents/smm

INCLUDEDIRS=
INCLUDE=
LIBDIRS=
LIBS = -lm
OPTLVL = -O3

OBJECTS = ${original_objects}
CC=clang
CFLAGS = $(INCLUDEDIRS) $(INCLUDE) $(OPTLVL) -fno-inline
LDFLAGS = $(LIBDIRS) $(LIBS) -static

all: $(PROGRAM)

$(PROGRAM): $(OBJECTS) heap_allocator.bc
	llvm-link -o temp_$@.bc $(OBJECTS) heap_allocator.bc
	opt $(OPTLVL) -disable-inlining < temp_$@.bc > temp1_$@.bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMBase.so -smm-prolog < temp1_$@.bc > temp2_$@.bc
	opt -load $(HOME)/Applications/llvm-3.6.0/build/Debug+Asserts/lib/SMMBase.so -smm-cache --debug-only=smm-cache < temp2_$@.bc > $@.bc
	llvm-dis < $@.bc > $@.ll
	llc $(OPTLVL) -o $@.s $@.bc 
	$(CC) -o $@ $@.s $(LDFLAGS) -Wl,-T,cache.ld
	objdump -d $@ > $@.dis


%.bc: %${source_file_extension}
	$(CC) $(CFLAGS) -emit-llvm -c $< -o $@

heap_allocator.bc:$(SMMDIR)/heap/lib/malloc.c
	$(CC) -I$(SMMDIR)/common/include -I$(SMMDIR)/heap/include -include malloc.h $(CFLAGS) -emit-llvm -c $< -o $@

callgraph: $(PROGRAM)
	opt -dot-callgraph < $(PROGRAM).bc
	dot -Tpng callgraph.dot -o $(PROGRAM).png

clean:
	-rm -rf  $(PROGRAM) *.s *.o *.bc *.ll *.dis  ${outfile} *.png
    """
	# Create the makefile using the created linker script
	if (not os.path.isfile("Makefile")): 
		cwd = os.getcwd()
		files = os.listdir(cwd)
		objects = []
		source_file_extension = ""
		for i in range(len(files)):
			(file, extension) = os.path.splitext(files[i])
			if(extension == ".c" or extension == ".cpp" or extension == ".cc"):
				objects.append(file)
				if source_file_extension == "":
					source_file_extension = extension
		objects = list(set(objects))
		original_objects = ""
	   	for i in range(len(objects)):
			original_objects = original_objects + " " + objects[i] + ".bc"
		# Use the name of current folder as the name of generated executable file
		program = os.path.basename(cwd)
		with open('Makefile', 'w') as f:
			makefile = makefile.replace("${original_objects}", original_objects)
			makefile = makefile.replace("${program}", program)
			makefile = makefile.replace("${source_file_extension}", source_file_extension)
			makefile = makefile.replace("${outfile}", outfile)
			f.write(makefile)

# Create a makefile for cache-based setup
def create_linkerscript_cache():
	# Create the section for user functions
	custom_script = []
	#custom_script.append("\n\n  . = ALIGN(0x10);\n")
	custom_script.append("\n  . = ALIGN(0x100000);\n")
	#custom_script.append("\n  . = __executable_start + 0x100000;\n")
	custom_script.append("\n  _cacheable_begin = .;\n")

	custom_script.append("\n  _cacheable_code_begin = .;\n")
	custom_script.append("  _cacheable_code_end = _cacheable_code_begin + 0x100000;\n")
	custom_script.append("  .user_text : { *.(user_text) }\n")
	custom_script.append("  . = _cacheable_code_end;\n");

	custom_script.append("\n  _cacheable_data_begin = .;\n")
	custom_script.append("  _cacheable_data_end = _cacheable_data_begin + 0x100000;\n");
	custom_script.append("  .user_data : { *.(user_data) }\n")
	custom_script.append("  . = _cacheable_data_end;\n");

	custom_script.append("\n  _cacheable_stack_begin = .;\n")
	custom_script.append("  _cacheable_stack_end = _cacheable_stack_begin + 0x100000;\n")
	custom_script.append("  . = _cacheable_stack_end;\n");

	custom_script.append("\n  _cacheable_heap_begin = .;\n")
	custom_script.append("  _cacheable_heap_end = _cacheable_heap_begin + 0x100000;\n")
	custom_script.append("  . = _cacheable_heap_end;\n");


	custom_script.append("\n  _cacheable_end = .;\n")
	custom_script.append("\n  .smm-guard _cacheable_end : AT (_cacheable_end) { FILL(0x0) QUAD(0x0) QUAD(0x0) }\n\n");


	#print custom_script

	# Create the linker script with SPM
#	if (not os.path.isfile("spm.ld")): 
	with open('cache.ld', 'w') as linker_script:
		implicit_linker_script = subprocess.Popen("ld --verbose", stdout=subprocess.PIPE, shell=True).communicate()[0].split("\n")
		i = 0
		while i <  range(len(implicit_linker_script)):
	    		line = implicit_linker_script[i]
    			while (line.find("==================================================") == -1):
				i = i+1
				line = implicit_linker_script[i]
			i = i + 1
    			line = implicit_linker_script[i]
			while (line.find("==================================================") == -1):
				if line.find("executable_start") != -1:
					linker_script.write(line)
					linker_script.writelines(custom_script)
				else:
    					linker_script.write(line + "\n")
				i = i+1
				line = implicit_linker_script[i]
			break;



# Create a makefile for using hardware caching
def create_makefile_icache(arguments="", infile = "", outfile=""):
	#  make file
	makefile = """
PROGRAM = ${program}

INCLUDEDIRS=
INCLUDE=
LIBDIRS=
LIBS = -lm
OPTLVL = -O3

OBJECTS = ${original_objects}
CC=clang
CFLAGS = $(INCLUDEDIRS) $(INCLUDE) $(OPTLVL) -fno-inline
LDFLAGS = $(LIBDIRS) $(LIBS) -static

all: $(PROGRAM)

$(PROGRAM): $(OBJECTS)
	llvm-link -o temp_$@.bc $(OBJECTS)
	opt $(OPTLVL) -disable-inlining < temp_$@.bc > $@.bc
	llvm-dis < $@.bc > $@.ll
	llc $(OPTLVL) -o $@.s $@.bc 
	$(CC) -o $@ $@.s $(LDFLAGS) -Wl,-T,cache.ld
	objdump -d $@ > $@.dis



%.bc: %${source_file_extension}
	$(CC) $(CFLAGS) -emit-llvm -c $< -o $@

callgraph: $(PROGRAM)
	opt -dot-callgraph < $(PROGRAM).bc
	dot -Tpng callgraph.dot -o $(PROGRAM).png

clean:
	-rm -rf  $(PROGRAM) *.bc *.ll *.s *.dis *.dot *.png ${outfile} 
    """

	# Create the linker script for SPM setup
	if (not os.path.isfile("spm.ld")): 
		with open('spm.ld', 'w') as outFile:
			inFile = subprocess.Popen("ld --verbose", stdout=subprocess.PIPE, shell=True).communicate()[0].split("\n")
			i = 0
			while i <  range(len(inFile)):
		    		line = inFile[i]
    				while (line.find("==================================================") == -1):
					i = i+1
					line = inFile[i]
				i = i + 1
    				line = inFile[i]
				while (line.find("==================================================") == -1):
					if line.find("executable_start") != -1:
					  	outFile.write(line.replace("0x400000", "0x000000") + "\n  . = ALIGN(0x10); \n  _spm_begin = .;\n  . = . + 0x100000;\n  _spm_end = .;\n  . = _spm_begin; \n  .spm           : { *(.spm) }\n  . = _spm_end;\n")
					else:
    						outFile.write(line + "\n")
					i = i+1
					line = inFile[i]
				break;

	# Create the makefile using the created linker script
	if (not os.path.isfile("Makefile")): 
		cwd = os.getcwd()
		files = os.listdir(cwd)
		objects = []
		source_file_extension = ""
		for i in range(len(files)):
			(file, extension) = os.path.splitext(files[i])
			if(extension == ".c" or extension == ".cpp" or extension == ".cc"):
				objects.append(file)
				if source_file_extension == "":
					source_file_extension = extension
		objects = list(set(objects))
		original_objects = ""
	   	for i in range(len(objects)):
			original_objects = original_objects + objects[i] + ".bc" + " "
		# Use the name of current folder as the name of generated executable file
		program = os.path.basename(cwd)
		with open('Makefile', 'w') as f:
			# make + make opt
			makefile = makefile.replace("${original_objects}", original_objects)
			makefile = makefile.replace("${program}", program)
			makefile = makefile.replace("${source_file_extension}", source_file_extension)
			# make clean
			if (outfile == ""):
				arg_list = arguments.split()
    				for i in range(len(arg_list)):
					if "output" in arg_list[i]:
						outfile = arg_list[i] 
			makefile = makefile.replace("${outfile}", outfile)
			# make prof
			makefile = makefile.replace("${arguments}", arguments)
			if (infile != ""):
				makefile = makefile.replace("${infile}", "< " + infile)
			else:
				makefile = makefile.replace("${infile}", "")
			f.write(makefile)

def create_runme_cache(dsize = "", isize = "", arguments="", infile="", outfile=""):
	program = os.path.basename(os.getcwd())
	# Create a runme script
	if (not os.path.isfile("runme")):
		with open("runme", "w") as f:
			prolog = "#!/bin/sh\nWORK=$HOME\nSIMDIR=$WORK/Applications/gem5-cache"
			text = "$SIMDIR/build/X86/gem5.opt -r -d m5out/cache $SIMDIR/configs/example/se.py  --cpu-type=atomic --caches -c " + program
			if (arguments != ""):
				text = text + " -o \"" + arguments + "\""
			if (infile != ""):
				text = text + " --input=\"" + infile + "\""
			if (outfile != ""):
				text = text + " --output=\"" + outfile + "\""
			if (dsize != ""):
				text = text + " --l1d_size=\"" + dsize +"\""
			if (isize != ""):
				text = text + " --l1i_size=\"" + isize +"\""
			f.write(prolog + "\n")
			f.write(text + "\n")
    		subprocess.Popen("chmod +x runme", stdout=subprocess.PIPE, shell=True)

		

# Get options
if __name__ == "__main__":
	try:
		opts, args = getopt.getopt(sys.argv[1:], "-h", ["help", "configure-cache", "configure-icache", "configure-stack", "configure-array", "configure-code", "configure-spm", "configure-spm-linkerscript=", "stack-size=", "tile=", "code-size=", "num-regions=", "args=", "input=", "output=", "clean", "l1d_size=", "l1i_size="]) 
	except getopt.GetoptError as err:
		print str(err)
		sys.exit(2)
	arguments = ""
	infile = ""
	outfile = ""
	config = 0
	stacksize = 0
	tile = 0
	codesize = 0
	numregions = 0
	overlaying = ""
	dsize = ""
	isize = ""
	for opt, arg in opts:
		if opt in ("-h", "--help"):
			print 'smmmake --configure-cache --configure-icache --configure-stack --configure-array --configure-code --configure-spm --stack-size --tile --code-size --num-regions --args --input --output --clean --l1d_size --l1i_size'
			sys.exit()
		elif opt in ("--configure-cache"):
			config = 1
		elif opt in ("--configure-icache"):
			config = 2
		elif opt in ("--configure-stack"):
			config = 3
		elif opt in ("--configure-array"):
			config = 4
		elif opt in ("--configure-code"):
			config = 5
		elif opt in ("--configure-spm"):
			config = 6
		elif opt in ("--configure-spm-linkerscript"):
			config = 7
			overlaying = arg
		elif opt in ("--args"):
			arguments = arg
		elif opt in ("--input"):
			infile = arg
		elif opt in ("--output"):
			outfile = arg
		elif opt in("--stack-size"):
			stacksize = arg
		elif opt in("--code-size"):
			codesize = arg
		elif opt in("--tile"):
			tile = arg
		elif opt in("--num-regions"):
			numregions = arg
		elif opt in ("--clean"):
			if (os.path.isfile("spm.ld")):
    				subprocess.Popen("rm spm.ld", stdout=subprocess.PIPE, shell=True)
			if (os.path.isfile("cache.ld")):
    				subprocess.Popen("rm cache.ld", stdout=subprocess.PIPE, shell=True)
			if (os.path.isfile("Makefile")):
    				subprocess.Popen("rm Makefile", stdout=subprocess.PIPE, shell=True)
			if  len(glob.glob("*runme*")) > 0:
    				subprocess.Popen("rm *runme*", stdout=subprocess.PIPE, shell=True)
#			if (os.path.isdir("m5out")):
#    				subprocess.Popen("rm -r m5out", stdout=subprocess.PIPE, shell=True)
		elif opt in ("--l1d_size"):
		      	dsize = arg
		elif opt in ("--l1i_size"):
		      	isize = arg
		else:
			assert False, "unhandled option"

	if config == 1:
		create_makefile_cache(outfile)
		create_linkerscript_cache()
		create_runme_cache(dsize, isize, arguments, infile, outfile)
    	if config == 2:
		create_makefile_icache(arguments, infile, outfile)
		create_runme_cache(dsize, isize, arguments, infile, outfile)
	if config == 3:
		create_makefile_spm(arguments, infile, outfile, stacksize, 0, 0, 0)
    		create_linkerscript_spm()
		create_runme_smmstack(arguments, infile, outfile)
	if config == 4:
		create_makefile_spm(arguments, infile, outfile, 0, 0, 0, tile)
    		create_linkerscript_spm()
		create_runme_smmarray(arguments, infile, outfile)
    	if config == 5:
		create_makefile_spm(arguments, infile, outfile, 0, codesize, numregions, 0)
		create_runme_smmcode(arguments, infile, outfile)
    	if config == 6:
		create_makefile_spm(arguments, infile, outfile, stacksize, codesize, numregions, tile)
    		create_linkerscript_spm()
		create_runme_smmapp(arguments, infile, outfile, dsize, isize)
		create_runme_smmstack(arguments, infile, outfile, dsize, isize)
		create_runme_smmarray(arguments, infile, outfile, dsize, isize)
    	if config == 7:
		create_linkerscript_spm(overlaying)

